---
- name: "Install sync-hwclock timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: enable a timer for sync-hwclock
  with_items:
  - "sync-hwclock.service"
  - "sync-hwclock.timer"
