---
- hosts: all
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  pre_tasks:
  - name: "Install etckeeper"
    apt: name=etckeeper
  roles:
  - role: znzj.ja_jp
  - role: znz.ufw
    ufw_default_forward_policy: reject
    ufw_allow_in_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "HTTPS"
      port: 443
    ufw_allow_out_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "SSH"
      port: 22
    - comment: "SMTPS"
      port: 465
  - role: znz.journald
  - role: znz.sshd
  - role: znz.postfix-relay-only
    when: postfix_relay_smtp_server is not none and postfix_relay_smtp_server != ""
  - role: logcheck
  - role: znz.unattended-upgrades
  - role: znz.nadoka
    when: nadoka_irc_host is not none and nadoka_irc_host != ""
  - role: byobu
  tasks:
  - name: 'Comment out 127.0.1.1 in /etc/hosts'
    replace:
      path: /etc/hosts
      regexp: '^(127\.0\.1\.1)'
      replace: '#\1'
  - name: 'Update /etc/hosts'
    lineinfile:
      path: /etc/hosts
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ stage_etc_hosts }}"
  - name: 'Install logwatch'
    apt: name=logwatch

- hosts: gitlab
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: letsencrypt
  - role: znz.gitlab-ce
    gitlab_omnibus_config: "{{ stage_gitlab_omnibus_config }}"
  - role: znz.sshd
    sshd_allow_users:
    - 'git'

- hosts: gitlab-runner
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.docker
    docker_daemon_config: "{{ stage_gitlab_runner_docker_daemon_config }}"
  - role: znz.gitlab-runner
    gitlab_runner_coordinator_url: "{{ stage_gitlab_runner_coordinator_url }}"
    gitlab_runner_register_options: "{{ stage_gitlab_runner_register_options }}"
    gitlab_runner_tags: "{{ stage_gitlab_runner_tags }}"
  - role: docker-dns
    dns: "{{ stage_docker_dns[ansible_hostname] }}"
  tasks:
  - name: "Set concurrent of gitlab runner"
    lineinfile:
      path: "/etc/gitlab-runner/config.toml"
      regexp: '^concurrent = '
      line: "concurrent = {{ stage_gitlab_runner_concurrent }}"

- hosts: dokku
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.docker
    docker_daemon_config: "{{ stage_dokku_daemon_config }}"
  - role: znz.dokku
    dokku_vhost_enable: "true"
    dokku_web_config: "false"
    dokku_hostname: "{{ stage_dokku_hostname }}"
    dokku_skip_key_file: "{{ stage_dokku_skip_key_file }}"
    dokku_key_file: "{{ stage_dokku_key_file }}"
    dokku_plugin: "{{ stage_dokku_plugin }}"
  - role: docker-dns
    dns: "{{ stage_docker_dns[ansible_hostname] }}"
  - role: znz.sshd
    sshd_allow_users:
    - 'dokku'
  tasks:
  - name: 'ufw allow out on docker0 proto tcp'
    # allow nginx to app
    ufw:
      direction: out
      interface: docker0
      proto: tcp
      rule: allow
