---
- name: "Install dokku dokku-leak-stop timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: enable a timer for dokku-leak-stop
  with_items:
  - "dokku-leak-stop.service"
  - "dokku-leak-stop.timer"
