---
- hosts: all
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  pre_tasks:
  - name: "Install etckeeper"
    apt: name=etckeeper
  roles:
  - role: znzj.ja_jp
  - role: znz.ufw
    ufw_default_forward_policy: reject
    ufw_allow_in_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "HTTPS"
      port: 443
    ufw_allow_out_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "SSH"
      port: 22
  tasks:
  - name: 'Comment out 127.0.1.1 in /etc/hosts'
    replace:
      path: /etc/hosts
      regexp: '^(127\.0\.1\.1)'
      replace: '#\1'
  - name: 'Update /etc/hosts'
    lineinfile:
      path: /etc/hosts
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ stage_etc_hosts }}"

- hosts: gitlab
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: letsencrypt
  - role: znz.gitlab-ce
    gitlab_omnibus_config: "{{ stage_gitlab_omnibus_config }}"

- hosts: gitlab-runner
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.docker
    docker_daemon_config: "{{ stage_gitlab_runner_docker_daemon_config }}"
  - role: znz.gitlab-runner
    gitlab_runner_coordinator_url: "{{ stage_gitlab_runner_coordinator_url }}"
    gitlab_runner_register_options: "{{ stage_gitlab_runner_register_options }}"
  - role: docker-dns
    dns: "{{ stage_docker_dns[ansible_hostname] }}"

- hosts: dokku
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.docker
  - role: znz.dokku
    dokku_vhost_enable: "true"
    dokku_web_config: "false"
    dokku_hostname: "{{ stage_dokku_hostname }}"
    dokku_skip_key_file: "{{ stage_dokku_skip_key_file }}"
    dokku_key_file: "{{ stage_dokku_key_file }}"
  - role: docker-dns
    dns: "{{ stage_docker_dns[ansible_hostname] }}"
  tasks:
  - name: 'ufw allow out on docker0 proto tcp'
    # allow nginx to app
    ufw:
      direction: out
      interface: docker0
      proto: tcp
      rule: allow
