---
- name: "Install postfix"
  apt:
    name: postfix
- name: "Update /etc/postfix/main.cf"
  lineinfile:
    path: "/etc/postfix/main.cf"
    regexp: "^relayhost = "
    line: "relayhost = [{{ postfix_relay_smtp_server }}]:{{ postfix_relay_smtp_port }}"
  notify: reload postfix
- name: "Update /etc/postfix/main.cf"
  lineinfile:
    path: "/etc/postfix/main.cf"
    regexp: "^{{ item.key }} = "
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ postfix_main_cf }}"
  notify: reload postfix
- name: "Update sasl_password"
  lineinfile:
    path: "/etc/postfix/sasl/sasl_password"
    line: "[{{ postfix_relay_smtp_server }}]:{{ postfix_relay_smtp_port }} {{ postfix_relay_smtp_user }}:{{ postfix_relay_smtp_pass }}"
    create: yes
    owner: "root"
    group: "postfix"
    mode: 0640
  notify: postmap sasl_password
